# COPYRIGHT Ericsson 2023
#
# The copyright to the computer program(s) herein is the property of
# Ericsson Inc. The programs may be used and/or copied only with written
# permission from Ericsson Inc. or in accordance with the terms and
# conditions stipulated in the agreement/contract under which the
# program(s) have been supplied.

version: '3.4'
services:
  arcoptimization:
    build:
      context: ../ArcSwU/
      network: host
    image: "arcapp:${version:-latest}"
    ports:
      - "5000:5000"
    logging:
      driver: "json-file"
      options:
        max-size: "2048m"
    container_name: arcoptimization_for_comp_test
    environment:
      - PYTHONUNBUFFERED=1

  optimization_component:
    build:
      context: .
      network: host
    image: "optimization_comp_test:${version:-latest}"
    container_name: opt_comp_test
    depends_on:
      - arcoptimization
