# COPYRIGHT Ericsson 2023
#
# The copyright to the computer program(s) herein is the property of
# Ericsson Inc. The programs may be used and/or copied only with written
# permission from Ericsson Inc. or in accordance with the terms and
# conditions stipulated in the agreement/contract under which the
# program(s) have been supplied.

# Build avoidance configuration file

files:
  # Lists of all file/directory dependencies in this repository relative to the
  # repo root, for build avoidance purpose.
  - ArcSwU/Pipfile
  - ArcSwU/Pipfile.lock
  - ArcSwU/ArcSrv
