# COPYRIGHT Ericsson 2023
#
# The copyright to the computer program(s) herein is the property of
# Ericsson Inc. The programs may be used and/or copied only with written
# permission from Ericsson Inc. or in accordance with the terms and
# conditions stipulated in the agreement/contract under which the
# program(s) have been supplied.

apiVersion: v1
kind: Secret
metadata:
  name: {{ include "eric-oss-cad-poc.name" . }}
  labels: {{- include "eric-oss-cad-poc.labels" . | nindent 4 }}
  annotations: {{- include "eric-oss-cad-poc.product-info" . | nindent 4 }}
stringData:
  CM_USERNAME: {{ .Values.configuration.cm.username }}
  CM_PASSWORD: {{ .Values.configuration.cm.password }}
  TOPOLOGY_USERNAME: {{ .Values.configuration.topology.username }}
  TOPOLOGY_PASSWORD: {{ .Values.configuration.topology.password }}
  MONGO_USERNAME: {{ .Values.configuration.mongo.username }}
  MONGO_PASSWORD: {{ .Values.configuration.mongo.password }}
