# COPYRIGHT Ericsson 2023
#
# The copyright to the computer program(s) herein is the property of
# Ericsson Inc. The programs may be used and/or copied only with written
# permission from Ericsson Inc. or in accordance with the terms and
# conditions stipulated in the agreement/contract under which the
# program(s) have been supplied.

productName: "eric-ran-rapp-cad-optimization"
productNumber: "CXU1011706/1"
images:
  cadOptimization:
    productName: "ARC Optimization Service"
    productNumber: "CXU1011706/1"
    registry: "armdocker.rnd.ericsson.se"
    repoPath: "proj-rapp-ai-inter-bb-coordination"
    name: "arcoptimization"
    tag: "1.3.2"
  mongoDB:
    productName: "Official MongoDB"
    productNumber: "XXX0000000/1"
    registry: "armdocker.rnd.ericsson.se"
    repoPath: "dockerhub-ericsson-remote/bitnami"
    name: "mongodb"
    tag: "6.0.2"
